// src/models/applicationModel.ts
export interface Application {
  id?: string; // Auto-generated by Cosmos DB
  jobId: string;
  jobTitle: string;
  jobLocation: string; // Partition Key for this application item
  companyName: string;
  applicantName: string;
  applicantEmail: string;
  applicantPhone: string;
  resumeUrl?: string; // Optional
  coverLetterNotes?: string; // Optional field for brief notes from applicant
  posterEmail: string; // Email of the job poster
  applicationDate: string; // ISO string
  status: "Submitted" | "Viewed" | "Contacted" | "Rejected"; // Example statuses
}