export interface Job {
    id?: string; // Optional because it will be auto-generated by Cosmos DB
    title: string; // Job title (mandatory)
    description: string; // Detailed job description (mandatory)
    responsibilities: string[]; // List of responsibilities (mandatory)
    location: string; // Job location (mandatory, used as the partition key)
    requiredEducation: string; // Minimum education required
    requiredSkills: string[]; // List of required skills
    languagesRequired?: string[]; // Optional, languages required for the job
    salaryRange: {
      min: number; // Minimum salary
      max: number; // Maximum salary
      unit: string; // Salary unit (e.g., "day", "month")
    };
    jobType: string; // Job type (e.g., "Part-Time", "Full-Time")
    workSchedule: string; // Work schedule/timings
    companyName: string; // Name of the company
    contactDetails: {
      email: string; // Employer email address
      phone?: string; // Optional phone number
    };
    tags?: string[]; // Optional tags/keywords for search
    perks?: string[]; // Optional perks/benefits
    applicationDeadline?: string; // Optional deadline for applying
    numberOfOpenings?: number; // Optional, total positions available
    status?: string; // Default "active"; can be "expired" in the future
    postedDate?: string; // Auto-generated when the job is created
    views?: number; // Default 0; incremented when the job is viewed
  }
  